name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.build.os }}
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        build:
        - os: macos-latest
          ostype: darwin
          arch: x64

        - os: macos-latest
          ostype: darwin
          arch: arm64

        - os: ubuntu-latest
          ostype: linux
          arch: x64

        - os: ubuntu-latest
          ostype: linux
          arch: arm64

        - os: ubuntu-latest
          ostype: linux
          arch: armv7l

        - os: windows-latest
          ostype: windows
          arch: ia32

        - os: windows-latest
          ostype: windows
          arch: x64

        - os: windows-latest
          ostype: windows
          arch: arm64

    name: Build (${{ matrix.build.ostype }} ${{ matrix.build.arch }})

    steps:
    - uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build -- --arch=${{ matrix.build.arch }}

