name: Publish

on:
  push:
    branches: [ github-actions ]
    
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    name: Build (${{ matrix.os }})

    steps:
    - uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        path: BloodHound-*
        name: binaries

  publish:
    name: Compress
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Download BloodHound binaries
      uses: actions/download-artifact@v2
      with:
        name: binaries

    - name: Zip
      uses: edgarrc/action-7z@v1
      with:
        args: |
        for pkg in $(ls -D); do
          7z a -tzip -mx9 ${pkg}-${GITHUB_SHA}.zip ${pkg}
        done
