name: Publish

on:
  push:
    branches: [ github-actions ]
    
jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Zip
      run: |
        for pkg in $(ls -D); do
          7z a -tzip -mx9 ${pkg}-${GITHUB_SHA}.zip ${pkg}
        done
